version: "3.8"

services:
  student-api:
    image: student-api:prod
    container_name: student-api-prod
    ports:
      - "3002:3000"
    environment:
      NODE_ENV: production
      PORT: "3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fss http://localhost:3000/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 12
      start_period: 10s
    restart: unless-stopped
